import { Noto_Sans_KR } from 'next/font/google';
import localFont from 'next/font/local';

import './globals.css';

const fontNotoSansKr = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
  variable: '--font-noto',
  display: 'swap',
});

const fontBaskin = localFont({
  src: './fonts/baskin-robbins-bold.woff2',
  variable: '--font-baskin',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="ko"
      className={`${fontNotoSansKr.variable} ${fontBaskin.variable}`}
    >
      <body className="flex min-h-full flex-col">
        <p className="font-baskin-base text-baskin-62-bold">제목</p>
        {children}
      </body>
    </html>
  );
}
